name: jobline
description: "Advanced Mobile Programming Team Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  image_picker: ^1.0.7
  cached_network_image: ^3.4.1
  flutter_doc_scanner: ^0.0.16
  permission_handler: ^11.3.1
  firebase_storage: ^12.4.10
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.6.12
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0
  flutter_layout_grid: ^2.0.4
  flutter_markdown: ^0.6.18


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
